### ISSUE TITLE
how to use node modules?

### ISSUE THREAD

**Issue by ramusbucket** [akoskm/vite-react-tailwindcss-browser-extension-simple#3]
I'm pretty now to the ecosystem of all the tools. I'm trying to integrate our crm into gmail with chrome addon. I'm having hard time to get it right.
first thing is when I cloned your repo and tried to load in browser as per instructions in the repo, i get following 

![image](https://user-images.githubusercontent.com/3519523/209242590-318fda13-5ab2-4199-b46c-141b589a8efc.png)

Secondly, how can I use browser compatible node_modules like inboxsdk in this project. Do I need configure Vite or something in the manifest to refer the path of this node module?

**Comment by ramusbucket** [comment]
Ok, instead of doing `npm run dev`, I decided to build it first and the load in browser. On windows, `npm run build:chrome` did not work as is. I had to change it to - `set NODE_ENV=production run-s build:js build:background:chrome build:web build:manifest:chrome`.  Basically, I prepended `set` to the existing command. My default VS Code shell is powershell 7.3.1

But still it would not generate index.global.js for some reason. So I ran all the commands one-by-one. After that it generated all those files. Now, when I load the dist folder in the extensions, I don't see the index page ui on blank tab.

**Comment by akoskm** [comment]
Hi!

The add-on needs to build differently for [Firefox](https://github.com/akoskm/vite-react-tailwindcss-browser-extension-simple#firefox) and [Chrome/Brave](https://github.com/akoskm/vite-react-tailwindcss-browser-extension-simple#chrome).

> On windows, npm run build:chrome did not work as is. I had to change it to - set NODE_ENV=production run-s build:js build:background:chrome build:web build:manifest:chrome. Basically, I prepended set to the existing command. My default VS Code shell is PowerShell 7.3.1
> 
> But still it would not generate index.global.js for some reason. So I ran all the commands one-by-one. After that it generated all those files.

This could be an issue between us using different platforms. It would be good to look at other cross-platform repos and see how they set environment variables. Would you happen to have an example?

> Now, when I load the dist folder in the extensions, I don't see the index page ui on blank tab.

The manifest files are specifically set to activate the plugin only on:

https://github.com/akoskm/vite-react-tailwindcss-browser-extension-simple/blob/a95d8e8545be47d3f80f87839bc2d95141276bd5/public/manifestv3.json#L12-L14

So just try to open `https://blank.org/` in a new tab, and the add-on should appear.

**Comment by akoskm** [comment]
Please reopen this if you have more questions. I'm happy to debug the issues you're having with this repo.
