### ISSUE TITLE
First build error - Could not resolve entry module (vite-react-tailwindcss-browser-extension-simple/popup.html)

### ISSUE THREAD

**Issue by harddownloader** [akoskm/vite-react-tailwindcss-browser-extension-simple#6]
![image](https://github.com/akoskm/vite-react-tailwindcss-browser-extension-simple/assets/55257833/3e8c02c1-8340-4a29-91a7-63a7173a3d11)
Hello guys!
I'm trying to do the first build of this repo, but I get an error:
Could not resolve entry module (../../browser%20extension/vite-react-tailwindcss-browser-extension-simple/popup.html).
error during build:
Error: Could not resolve entry module (../../browser%20extension/vite-react-tailwindcss-browser-extension-simple/popup.html).
    at error (file:///C:/Users/Pc/Desktop/browser%20extension/vite-react-tailwindcss-browser-extension-simple/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.loadEntryModule (file:///C:/Users/Pc/Desktop/browser%20extension/vite-react-tailwindcss-browser-extension-simple/node_modules/rollup/dist/es/shared/rollup.js:22175:20)
    at async Promise.all (index 0)
 

 Could you please help me with this? From your point of view, what could it be?
 p.s. I just did the next commands:
 npm init
 npm run build

platform: windows
node: 18.16.0

**Comment by akoskm** [comment]
Are you in the project's directory when trying to run these commands?

You also don't want `npm init` but `npm install` instead.

To me, this looks like a path problem – `../../browser%20extension` isn't part of the plugin, but something tries to access the `popup.html` through that directory.

**Comment by harddownloader** [comment]
Hi, yep, you're right.
It was a path-related problem.
I just changed the name of the folder that contains the cloned repository, from "browser extension" to "browser_extension".
Now it works.
Thanks a lot!
Have a good day!
![image](https://github.com/akoskm/vite-react-tailwindcss-browser-extension-simple/assets/55257833/a4913b37-39ce-4c05-8acc-bb7195e860f5)
